// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechnightApi.Data;

#nullable disable

namespace TechnightApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251202140559_FixSeedDataDates")]
    partial class FixSeedDataDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechnightApi.Models.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate")
                        .HasDatabaseName("ix_example_entry_date");

                    b.ToTable("example", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is the first example entry",
                            EntryDate = new DateTime(2025, 12, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "First Example",
                            Title = "Introduction"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is the second example entry",
                            EntryDate = new DateTime(2025, 12, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Second Example",
                            Title = "Advanced Topics"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
